"use client";
import { useEffect, useState } from "react";

const money = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n);

type Trade = { id: string; symbol: string; side: "BUY" | "SELL"; quantity: string | number; entryPrice: string | number; exitPrice?: string | number | null; pnl?: string | number | null; status: string; openedAt: string; closedAt?: string | null };

export default function TradesPage() {
  const [accountId, setAccountId] = useState(""); const [trades, setTrades] = useState<Trade[]>([]); const [symbol, setSymbol] = useState("EURUSD"); const [side, setSide] = useState<"BUY"|"SELL">("BUY"); const [qty, setQty] = useState("1"); const [price, setPrice] = useState("1.17420"); const [message, setMessage] = useState("");
  async function load() { if (!accountId) return; const r = await fetch(`/api/trades?accountId=${accountId}&pageSize=50`, { cache: "no-store" }); const j = await r.json(); if (r.ok) setTrades(j.data ?? []); else setMessage(j.error?.message ?? "Unable to load trades"); }
  useEffect(() => { fetch("/api/accounts?pageSize=1").then(r=>r.json()).then(j=>{ const a=j.data?.[0]; if(a){setAccountId(a.id);} }).catch(()=>{}); }, []);
  useEffect(() => { load(); }, [accountId]);
  async function openTrade() { setMessage(""); const r=await fetch("/api/trades",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accountId,symbol,side,quantity:Number(qty),entryPrice:Number(price)})}); const j=await r.json(); setMessage(r.ok?"Trade opened successfully":j.error?.message??"Could not open trade"); if(r.ok) load(); }
  async function closeTrade(t: Trade) { const exit=window.prompt(`Exit price for ${t.symbol}`, String(t.entryPrice)); if(!exit) return; const r=await fetch("/api/trades",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({tradeId:t.id,exitPrice:Number(exit)})}); const j=await r.json(); setMessage(r.ok?"Trade closed successfully":j.error?.message??"Could not close trade"); if(r.ok) load(); }
  return <div className="mx-auto max-w-[1400px] space-y-5"><div><h1 className="text-3xl font-semibold">Trades</h1><p className="mt-1 text-sm text-text-secondary">Open, monitor and close simulated challenge trades.</p></div>
    <section className="rounded-2xl border border-border bg-surface/80 p-5"><h2 className="font-medium">Open trade</h2><div className="mt-4 grid gap-3 md:grid-cols-5"><select value={side} onChange={e=>setSide(e.target.value as "BUY"|"SELL")} className="rounded-xl border border-border bg-background p-3"><option>BUY</option><option>SELL</option></select><input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} className="rounded-xl border border-border bg-background p-3" placeholder="Symbol"/><input value={qty} onChange={e=>setQty(e.target.value)} className="rounded-xl border border-border bg-background p-3" placeholder="Quantity"/><input value={price} onChange={e=>setPrice(e.target.value)} className="rounded-xl border border-border bg-background p-3" placeholder="Entry price"/><button onClick={openTrade} disabled={!accountId} className="rounded-xl bg-crimson px-4 py-3 font-semibold text-white disabled:opacity-50">Place trade</button></div>{message&&<p className="mt-3 rounded-xl border border-border p-3 text-sm text-text-secondary">{message}</p>}</section>
    <section className="rounded-2xl border border-border bg-surface/80 p-5"><div className="flex items-center justify-between"><h2 className="font-medium">Trade history</h2><button onClick={load} className="text-sm text-cyan">Refresh</button></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="border-b border-border text-xs text-text-muted"><tr>{["Symbol","Side","Qty","Entry","Exit","Status","P&L","Action"].map(x=><th key={x} className="pb-3 text-left">{x}</th>)}</tr></thead><tbody>{trades.map(t=><tr key={t.id} className="border-b border-border/60"><td className="py-4 font-semibold">{t.symbol}</td><td className={t.side==="BUY"?"py-4 text-cyan":"py-4 text-crimson"}>{t.side}</td><td className="py-4 font-mono">{t.quantity}</td><td className="py-4 font-mono">{t.entryPrice}</td><td className="py-4 font-mono">{t.exitPrice??"—"}</td><td className="py-4">{t.status}</td><td className="py-4 font-mono">{t.pnl==null?"—":money(Number(t.pnl))}</td><td className="py-4">{t.status==="OPEN"&&<button onClick={()=>closeTrade(t)} className="rounded-lg border border-border px-3 py-1.5 text-xs hover:border-cyan">Close</button>}</td></tr>)}{!trades.length&&<tr><td colSpan={8} className="py-10 text-center text-text-muted">No trades yet.</td></tr>}</tbody></table></div></section></div>;
}